# Variable substitution
# https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
# 環境変数は local/Makefile で設定されています。
version: "3.7"
name: "govelte-todo_mw_localdev"
services:
  apisvr:
    build:
      context: ../../backends/apisvr
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_APISVR_GRPC}:${APP_PORT_APISVR_GRPC}"
    networks:
      - network1

  uisvr:
    build:
      context: ../../frontends/uisvr
      dockerfile: Dockerfile
    environment:
      - PORT=${APP_PORT_UISVR_HTTP}
      - APP_FIREBASE_API_KEY=${APP_FIREBASE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${VITE_GOOGLE_CLOUD_PROJECT}
      - VITE_GOOGLE_CLOUD_PROJECT=${VITE_GOOGLE_CLOUD_PROJECT}
      - FIREBASE_AUTH_EMULATOR_HOST=${VITE_FIREBASE_AUTH_EMULATOR_HOST}
      - VITE_FIREBASE_AUTH_EMULATOR_HOST=${VITE_FIREBASE_AUTH_EMULATOR_HOST}
    ports:
      - "${APP_PORT_UISVR_HTTP}:${APP_PORT_UISVR_HTTP}"
    volumes:
      - ./frontends/uisvr/.env:/srv/uisvr/.env
    networks:
      - network1

  firebase-emulators:
    build:
      context: ../../middlewares/local/firebase-emulators
      dockerfile: Dockerfile
    ports:
      - "${APP_FIREBASE_AUTH_PORT}:9099"
      - "${APP_FIREBASE_EMULATOR_SUITE_PORT}:4000"
    volumes:
      - ./data/firebase-emulators:/srv/firebase-emulators/data
    networks:
      - network1
    command: firebase emulators:start --import /srv/firebase-emulators/data/firebase --export-on-exit /srv/firebase-emulators/data/firebase

networks:
  network1:
